[package]
name = "abi-test"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ethabi = "16.0.0"
ethabi-contract = "16.0.0"
ethabi-derive = "16.0.0"
hex = "0.4"
hex-literal = "0.3"
